### ISSUE TITLE
The windows build

### ISSUE THREAD

**Issue by sixtyfive** [nacho/gedit#1]
Hi nacho! 

Not a real issue, I guess, but I didn't know how else to contact you (followed the trail of breadcrumbs from https://wiki.gnome.org/Apps/Gedit over http://ftp.gnome.org/pub/GNOME/binaries/win64/gedit/ finally to here).

Anyways, the currently available Gedit build of version 3.22 for Windows works well enough, even under Windows 10. Unfortunately it's quite low in search engine results and a couple of places that claim to let you download Gedit for Windows look shady to me. Also, Linux users of most distros are by now on 3.32.2.

My real reason for writing, though, is that Gedit seems to be the only text editor for Windows where BiDi works properly (i.e., lines like `name: أحمد` looking _and working_ the way they're supposed to).

Is there any way you could create an updated build and document the process somewhere in an `.md` file or a Wiki page or so?

Cheers,
sixtyfive

**Comment by nacho** [comment]
Hi @sixtyfive, unfortunately I do not have the time to work anymore on gedit. In any case you could use msys2 to get an updated gedit.

**Comment by sixtyfive** [comment]
So, that's what you did back then? "Just" compile it with msys2, no C programming knowledge required?

**Comment by nacho** [comment]
yeah, there should be a script that does everything for you in the gedit git repository
